all: main.cpp Chaining.cpp ChainProcess.cpp HashTable.cpp OpenAddressing.cpp OpenProcess.cpp
	g++ -std=c++11 main.cpp Chaining.cpp ChainProcess.cpp HashTable.cpp OpenAddressing.cpp OpenProcess.cpp

clean:
	$(RM) a.out
